version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: realworldmapgen-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    restart: unless-stopped
    networks:
      - mapgen-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realworldmapgen-backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - generated_maps:/app/output
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - PYTHONUNBUFFERED=1
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - mapgen-network

  frontend:
    image: nginx:alpine
    container_name: realworldmapgen-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mapgen-network

volumes:
  ollama_data:
  generated_maps:

networks:
  mapgen-network:
    driver: bridge
