services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: realworldmapgen-backend
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
      - generated_maps:/app/output
    environment:
      - OLLAMA_HOST=http://host.docker.internal:11434
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    networks:
      - mapgen-network

  frontend:
    image: nginx:alpine
    container_name: realworldmapgen-frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - mapgen-network

volumes:
  generated_maps:

networks:
  mapgen-network:
    driver: bridge
